# Storage definition for Jeff.
# - Creates two buckets: b-jeff (private) and b-jeff-shared (discoverable).
# - Requests access to Joe's bucket b-joe.
# - Grants Joe ReadWrite access to b-jeff-shared.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-jeff
spec:
  principal: jeff
  buckets:
  - bucketName: b-jeff
  - bucketName: b-jeff-shared
    discoverable: true
  bucketAccessRequests:
  - bucketName: b-joe
    reason: Need access
  bucketAccessGrants:
  - bucketName: b-jeff-shared
    grantee: joe
    permission: ReadWrite
---
# Storage definition for Joe.
# - Creates one discoverable bucket: b-joe.
# - Requests access to Jeff's bucket b-jeff-shared.
# - Grants Jeff ReadWrite access to b-joe.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-joe
spec:
  principal: joe
  buckets:
  - bucketName: b-joe
    discoverable: true
  bucketAccessRequests:
  - bucketName: b-jeff-shared
    reason: Need access
  bucketAccessGrants:
  - bucketName: b-joe
    grantee: jeff
    permission: ReadWrite
