# Storage definition for Joe.
# - Creates one discoverable bucket: s-joe.
# - Requests access to Jeff's bucket s-jeff-shared.
# - Grants Jeff ReadWrite access to s-joe.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-joe
spec:
  principal: joe
  buckets:
    - bucketName: s-joe
      discoverable: true
  bucketAccessRequests:
    - bucketName: s-jeff-shared
      reason: Need access
      requestedAt: "2025-09-29T10:00:00Z"
  bucketAccessGrants:
    - bucketName: s-joe
      grantee: jeff
      permission: ReadWrite
      grantedAt: "2025-09-29T10:05:00Z"
