# Storage definition for Jeff.
# - Creates two buckets: s-jeff (private) and s-jeff-shared (discoverable).
# - Requests access to Joe's bucket s-joe.
# - Grants Joe ReadOnly access to s-jeff-shared.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-jeff
spec:
  principal: jeff
  buckets:
    - bucketName: s-jeff
    - bucketName: s-jeff-shared
      discoverable: true
  bucketAccessRequests:
    - bucketName: s-joe
      reason: Need access
      requestedAt: "2025-09-29T10:10:00Z"
  bucketAccessGrants:
    - bucketName: s-jeff-shared
      grantee: joe
      permission: ReadOnly
      grantedAt: "2025-09-29T10:15:00Z"
