---
# Storage definition for Jane.
# - Creates no buckets.
# - Requests access to John's bucket b-john (stated need: WriteOnly).
# - Note: This is only a request; access becomes effective only after John grants it.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-jane
spec:
  principal: jane
  buckets: []
  bucketAccessRequests:
  - bucketName: b-john
    reason: Need WriteOnly access
