# Storage definition for John.
# - Creates one bucket: s-john (private by default).
# - Requests access to s-joe (discoverable), s-jeff (private), and s-jane (not existing).
# - Grants Jane WriteOnly access to s-john.
# - Note: Outbound requests are active; access depends on the respective owners granting it.
#   The request to s-jane cannot resolve until that bucket exists.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-john
spec:
  principal: john
  buckets:
    - bucketName: s-john
  bucketAccessRequests:
    - bucketName: s-joe
      reason: Need access
      requestedAt: "2025-09-29T10:25:00Z"
    - bucketName: s-jeff
      reason: Need access
      requestedAt: "2025-09-29T10:26:00Z"
    - bucketName: s-jane
      reason: Need access
      requestedAt: "2025-09-29T10:27:00Z"
  bucketAccessGrants:
    - bucketName: s-john
      grantee: jane
      permission: WriteOnly
      grantedAt: "2025-09-29T10:28:00Z"
