# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

# John owns s-john. He grants Jane WriteOnly access to his bucket after her request.
# His request to s-jane cannot resolve until that bucket exists.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: s-john
spec:
  principal: john
  buckets:
    - bucketName: s-john
      discoverable: true
  bucketAccessRequests:
    - bucketName: s-joe
      reason: Need access
      requestedAt: "2025-09-29T10:25:00Z"
    - bucketName: s-jeff
      reason: Need access
      requestedAt: "2025-09-29T10:26:00Z"
    - bucketName: s-jane
      reason: Need access
      requestedAt: "2025-09-29T10:27:00Z"
  bucketAccessGrants:
    - bucketName: s-john
      grantee: jane
      permission: None
      grantedAt: "2025-09-29T10:28:00Z"
