default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: copyright-header
        name: Copyright header
        entry: ./scripts/copyright.py
        language: system
        types_or: [yaml]
