apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: provider-storage
  annotations:
    meta.crossplane.io/maintainer: ""
    meta.crossplane.io/source: "github.com/versioneer-tech/provider-storage"
    meta.crossplane.io/license: ""
    meta.crossplane.io/description: "Crossplane configuration to provision S3 compatible buckets with fine grained permissions for MinIO."
    meta.crossplane.io/readme: "github.com/versioneer-tech/provider-storage/blob/main/README.md"
spec:
  dependsOn:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      package: xpkg.upbound.io/vshn/provider-minio
      version: ">=v0.4.4"
  crossplane:
    version: ">=v1.20.0"
