site_name: provider-storage
site_url: https://versioneer-tech.github.io/provider-storage/
nav:
  - Home: index.md
  - Tutorials:
    - storage-minio: tutorials/storage-minio.md
  - How-to guides:
    - storage-minio: how-to-guides/storage-minio.md
  - Reference guides:
    - API: reference-guides/api.md
plugins:
  - search
  - mike
markdown_extensions:
  - admonition
theme:
  name: material
extra:
  version:
    provider: mike
