site_name: provider-storage
site_url: https://versioneer-tech.github.io/provider-storage/
nav:
  - Home: index.md
  - Tutorials:
    - storage-minio: tutorials/storage-minio.md
    - storage-aws: tutorials/storage-aws.md
    - storage-scaleway: tutorials/storage-scaleway.md
  - How-to guides:
    - general: how-to-guides/general.md
    - storage-minio: how-to-guides/storage-minio.md
    - storage-aws: how-to-guides/storage-aws.md
    - storage-scaleway: how-to-guides/storage-scaleway.md
  - Discussions:
    - Permission Workflow: discussions/permission-workflow.md
  - Reference guides:
    - API: reference-guides/api.md
plugins:
  - search
  - mike
markdown_extensions:
  - admonition
theme:
  name: material
  features:
  - content.code.copy
extra:
  version:
    provider: mike
