# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: storages.pkg.internal
spec:
  group: pkg.internal
  names:
    kind: Storage
    plural: storages
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: >
                Desired configuration of a Storage resource. Defines which buckets are
                created under the principal, which external buckets are requested,
                and which grants are issued to other principals.
              properties:
                principal:
                  type: string
                  description: >
                    Unique identifier of the storage principal (typically a user or
                    service account). All buckets, access requests, and grants in
                    this resource are owned and managed under this principal.
                credentialsRollover:
                  type: object
                  description: >
                    Configuration controlling automated rotation of access credentials
                    issued for this storage principal.
                  properties:
                    interval:
                      type: string
                      description: >
                        Defines how often access credentials are rotated. If set to none
                        credentials are not rotated automatically.
                      enum:
                        - daily
                        - weekly
                        - monthly
                        - quarterly
                        - yearly
                        - none
                      default: none
                    maxToKeep:
                      type: integer
                      description: >
                        Maximum number of previous credentials that remain valid after
                        a rollover. Older credentials beyond this limit are removed.
                      default: 1
                      minimum: 1
                      maximum: 10
                  required:
                    - interval
                    - maxToKeep
                buckets:
                  type: array
                  description: >
                    Buckets to create as part of this Storage. Each entry is keyed by
                    bucketName, ensuring uniqueness within the resource. Ordering
                    has no semantic meaning.
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: ["bucketName"]
                  items:
                    type: object
                    properties:
                      bucketName:
                        type: string
                        description: >
                          Name of the bucket to create. This value acts as the unique
                          key for the list element.
                      discoverable:
                        type: boolean
                        description: >
                          If true, the bucket is advertised for discovery by other
                          principals. Defaults to false when omitted.
                        default: false
                    required:
                      - bucketName
                bucketAccessRequests:
                  type: array
                  description: >
                    Outbound requests for access to buckets owned by other principals.
                    Each request originates from spec.principal and targets a single
                    foreign bucket. The list is keyed by bucketName.
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: ["bucketName"]
                  items:
                    type: object
                    properties:
                      bucketName:
                        type: string
                        description: >
                          Name of the bucket for which access is requested. This value
                          is the unique key for the request.
                      reason:
                        type: string
                        description: >
                          Optional free-text justification for the request. For
                          informational and auditing purposes only.
                      requestedAt:
                        type: string
                        format: date-time
                        description: >
                          RFC3339 timestamp indicating when the request was created.
                          Used to track request lifecycle. Typically set by the
                          controller.
                    required:
                      - bucketName
                      - requestedAt
                bucketAccessGrants:
                  type: array
                  description: >
                    Grants issued by this principal to other principals. Each grant is
                    uniquely identified by bucketName and grantee and defines the
                    permission level on the target bucket.
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: ["bucketName","grantee"]
                  items:
                    type: object
                    properties:
                      bucketName:
                        type: string
                        description: >
                          Name of the bucket for which the permission is granted.
                          This forms part of the unique key.
                      grantee:
                        type: string
                        description: >
                          Identifier of the principal receiving the grant. This forms
                          part of the unique key.
                      permission:
                        type: string
                        description: >
                          Permission level granted to the grantee on the specified
                          bucket. Setting None explicitly removes access.
                        enum:
                          - ReadWrite
                          - ReadOnly
                          - WriteOnly
                          - None
                      grantedAt:
                        type: string
                        format: date-time
                        description: >
                          RFC3339 timestamp indicating when the grant became active.
                          Used to track grant lifecycle. Typically set by the
                          controller.
                    required:
                      - bucketName
                      - grantee
                      - permission
                      - grantedAt
              required:
                - principal
                - buckets
            status:
              description: >
                Observed state of the Storage resource, including reconciliation
                results and any conditions applied by the controller.
              type: object
              properties: {}
