apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: storages.pkg.internal
spec:
  group: pkg.internal
  names:
    kind: Storage
    plural: storages
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Spec defines the desired state of a Storage resource.
              type: object
              properties:
                principal:
                  description: Identifier of the storage principal.
                  type: string
                buckets:
                  description: Buckets to create as part of this Storage.
                  type: array
                  items:
                    type: object
                    properties:
                      bucketName:
                        description: Name of the bucket to create.
                        type: string
                      discoverable:
                        description: Whether this bucket is discoverable in the catalog by others.
                        type: boolean
                        default: false
                    required:
                      - bucketName
                bucketAccessRequests:
                  description: Requests for access to buckets owned by others. Each request specifies the bucket name and a free-form reason.
                  type: array
                  items:
                    type: object
                    properties:
                      bucketName:
                        description: Name of the bucket to request access to.
                        type: string
                      reason:
                        description: Free-form text describing why access is requested.
                        type: string
                    required:
                      - bucketName
                bucketAccessGrants:
                  description: Grants of access permissions from this principal to other principals. Each entry specifies the bucket, the grantee, and the granted permission.
                  type: array
                  items:
                    type: object
                    properties:
                      bucketName:
                        description: Name of the bucket for which the permission is granted.
                        type: string
                      grantee:
                        description: Identifier of the principal receiving the permission.
                        type: string
                      permission:
                        description: Granted permission level.
                        type: string
                        enum:
                          - ReadWrite
                          - ReadOnly
                          - WriteOnly
                          - None
                    required:
                      - bucketName
                      - grantee
                      - permission
              required:
                - principal
                - buckets
            status:
              description: Status defines the observed state of a Storage resource.
              type: object
              properties: {}
