apiVersion: ops.crossplane.io/v1alpha1
kind: Operation
metadata:
  name: create-random-string
spec:
  mode: Pipeline
  pipeline:
    - step: create-random-string-config-map
      functionRef:
        name: crossplane-contrib-function-python
      requirements:
      input:
        apiVersion: python.fn.crossplane.io/v1beta1
        kind: Script
        script: |
          import uuid
          from crossplane.function import request

          def operate(req, rsp):
            observed_xr = req.observed.composite.resource
            length = 8
            random_string_1 = str(uuid.uuid4()).replace('-', '')[:length]
            random_string_2 = str(uuid.uuid4()).replace('-', '')[:length]
            rsp.desired.resources["random-string"].resource = {
              "apiVersion": "v1",
              "kind": "ConfigMap",
              "metadata": {
                "name": "random-string",
                "namespace": "crossplane-system"
              },
              "data": {
                "random-string": f"{random_string_1}-{random_string_2}"
              }
            }
