# Storage claim for principal Alice.
# - Buckets: "ws-alice" (personal) and "ws-alice-shared" (discoverable).
# - Access requests: wants access to Bob’s shared buckets (reasons provided).
# - Access grants: grants Bob and Eric permissions on "ws-alice-shared".
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-alice
spec:
  principal: ws-alice
  buckets:
  - bucketName: ws-alice
  - bucketName: ws-alice-shared
    discoverable: true
  bucketAccessRequests:
  - bucketName: ws-bob-share1
    reason: Needs to collaborate with Bob on dataset 1
  - bucketName: ws-bob-share2
    reason: Joint analysis with Bob on dataset 2
  bucketAccessGrants:
  - bucketName: ws-alice-shared
    grantee: ws-bob
    permission: ReadOnly
  - bucketName: ws-alice-shared
    grantee: ws-eric
    permission: ReadWrite
---
# Storage claim for principal Bob.
# - Buckets: "ws-bob" (personal), plus "ws-bob-share1" and "ws-bob-share2" (both discoverable).
# - Access requests: wants access to Alice’s shared bucket.
# - Access grants: grants Alice ReadWrite access to "ws-bob-share1".
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-bob
spec:
  principal: ws-bob
  buckets:
  - bucketName: ws-bob
  - bucketName: ws-bob-share1
    discoverable: true
  - bucketName: ws-bob-share2
    discoverable: true
  bucketAccessRequests:
  - bucketName: ws-alice-shared
    reason: Needs to integrate Alice’s data into analysis
  bucketAccessGrants:
  - bucketName: ws-bob-share1
    grantee: ws-alice
    permission: ReadWrite
---
# Storage claim for principal Eric.
# - Buckets: "ws-eric" (personal).
# - Access requests: wants access to Alice’s shared bucket.
# - No grants defined.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-eric
spec:
  principal: ws-eric
  buckets:
  - bucketName: ws-eric
  bucketAccessRequests:
  - bucketName: ws-alice-shared
    reason: Needs read access to Alice’s shared data
