# Storage claim for user Alice.
# - Buckets: "ws-alice" (personal) and "ws-alice-shared" (discoverable).
# - Access requests: wants ReadWrite access to Bob’s shared buckets.
# - Access grants: grants Bob and Eric ReadOnly access to "ws-alice-shared".
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-alice
spec:
  owner: alice
  buckets:
  - bucketName: ws-alice
  - bucketName: ws-alice-shared
    discoverable: true
  bucketAccessRequests:
  - bucketName: ws-bob-share1
    permission: ReadWrite
  - bucketName: ws-bob-share2
    permission: ReadWrite
  bucketAccessGrants:
  - bucketName: ws-alice-shared
    permission: ReadOnly
    grantees:
    - ws-bob
    - ws-eric
---
# Storage claim for user Bob.
# - Buckets: "ws-bob" (personal), plus "ws-bob-share1" and "ws-bob-share2" (both discoverable).
# - Access requests: wants ReadOnly access to Alice’s shared bucket.
# - Access grants: grants Alice ReadWrite access to "ws-bob-share1".
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-bob
spec:
  owner: bob
  buckets:
  - bucketName: ws-bob
  - bucketName: ws-bob-share1
    discoverable: true
  - bucketName: ws-bob-share2
    discoverable: true
  bucketAccessRequests:
  - bucketName: ws-alice-shared
    permission: ReadOnly
  bucketAccessGrants:
  - bucketName: ws-bob-share1
    permission: ReadWrite
    grantees:
    - ws-alice
---
# Storage claim for user Eric.
# - Buckets: "ws-eric" (personal).
# - Access requests: wants ReadWrite access to Alice’s shared bucket.
# - No grants defined.
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-eric
spec:
  owner: eric
  buckets:
  - bucketName: ws-eric
  bucketAccessRequests:
  - bucketName: ws-alice-shared
    permission: ReadWrite
