apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-alice
spec:
  owner: alice
  buckets:
  - bucketName: ws-alice
  - bucketName: ws-alice-shared
    discoverable: true
  bucketAccessRequests:
  - bucketName: ws-bob-share1
    permission: ReadWrite
  - bucketName: ws-bob-share2
    permission: ReadWrite
  bucketAccessGrants:
  - bucketName: ws-alice-shared
    permission: ReadOnly
    grantees:
    - ws-bob
    - ws-eric
---
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-bob
spec:
  owner: bob
  buckets:
  - bucketName: ws-bob
  - bucketName: ws-bob-share1
    discoverable: true
  - bucketName: ws-bob-share2
    discoverable: true
  bucketAccessRequests:
  - bucketName: ws-alice-shared
    permission: ReadOnly
  bucketAccessGrants:
  - bucketName: ws-bob-share1
    permission: ReadWrite
    grantees:
    - ws-alice
---
apiVersion: pkg.internal/v1beta1
kind: Storage
metadata:
  name: ws-eric
spec:
  owner: eric
  buckets:
  - bucketName: ws-eric
  bucketAccessRequests:
  - bucketName: ws-alice-shared
    permission: ReadWrite