# Copyright 2026, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: provider-ovh
spec:
  activate:
    - projectstorages.cloud.ovh.m.edixos.io
    - users.cloud.ovh.m.edixos.io
    - s3credentials.cloud.ovh.m.edixos.io
    - s3policies.cloud.ovh.m.edixos.io
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: provider-kubernetes
spec:
  activate:
    - objects.kubernetes.m.crossplane.io
