apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstorages.epca.eo
spec:
  group: epca.eo
  names:
    kind: XStorage
    plural: xstorages
  claimNames:
    kind: Storage
    plural: storages
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                buckets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      owner:
                        type: string
                      accessReadWrite:
                        type: array
                        items:
                          type: string
                      accessReadOnly:
                        type: array
                        items:
                          type: string
                  default: []
