# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: storage-minio
  annotations:
    meta.crossplane.io/maintainer: "Versioneer <info@versioneer.at>"
    meta.crossplane.io/source: "github.com/versioneer-tech/provider-storage"
    meta.crossplane.io/license: "Apache-2.0"
    meta.crossplane.io/description: "Crossplane configuration to provision S3 compatible buckets on MinIO with a workflow to request/access permissions."
    meta.crossplane.io/readme: "github.com/versioneer-tech/provider-storage/blob/main/README.md"
spec:
  # Intentionally no 'dependsOn' since GitOps based management of providers/functions is recommended
  skipDependencyResolution: true
  crossplane:
    version: ">=v2.0.2-0"