# Copyright 2026, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: provider-otc
spec:
  activate:
    - userv3s.identity.opentelekomcloud.crossplane.io
    - credentialv3s.identity.opentelekomcloud.crossplane.io
    - buckets.obs.opentelekomcloud.crossplane.io
    - bucketpolicies.obs.opentelekomcloud.crossplane.io
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: provider-kubernetes
spec:
  activate:
    - objects.kubernetes.m.crossplane.io
