# Copyright 2026, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-otc
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: provider-otc
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: provider-otc
      template:
        metadata:
          labels:
            runtime: provider-otc
        spec:
          containers:
          - name: package-runtime
            args:
            - --debug
            - --poll=1m
            resources:
              requests:
                cpu: 500m
                memory: 256Mi
              limits:
                cpu: "4"
                memory: 2Gi
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
spec:
  deploymentTemplate:
    metadata:
      labels:
        runtime: provider-kubernetes
    spec:
      replicas: 1
      selector:
        matchLabels:
          runtime: provider-kubernetes
      template:
        metadata:
          labels:
            runtime: provider-kubernetes
        spec:
          serviceAccountName: provider-kubernetes
          containers:
          - name: package-runtime
            args:
            - --poll=1m
            # - --debug
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
