# Copyright 2026, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: storage
data:
  storage:
    endpoint: https://obs.eu-nl.otc.t-systems.com
    provider: Other
    region: eu-nl
    type: s3
