apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes
  namespace: crossplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-kubernetes-otc
rules:
- apiGroups:
  - "identity.opentelekomcloud.crossplane.io"
  - "obs.opentelekomcloud.crossplane.io"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-kubernetes-otc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-kubernetes-otc
subjects:
- kind: ServiceAccount
  name: provider-kubernetes
  namespace: crossplane