name: Publish Provider Storage
on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+"
      - "[0-9]+\\.[0-9]+-alpha\\.[0-9]+"
      - "[0-9]+\\.[0-9]+-beta\\.[0-9]+"
      - "[0-9]+\\.[0-9]+-rc\\.[0-9]+"

jobs:
  build_and_publish_configuration_packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Install Crossplane CLI
        run: |
          curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/main/install.sh" | XP_VERSION=v2.0.2 sh
          sudo mv crossplane /usr/local/bin
      - name: Build and publish storage-minio Configuration Package
        run: |
          cp xrd.yaml minio/xrd.yaml
          crossplane xpkg build --package-root=minio --ignore="tests/observed/*,tests/expected/*" --package-file=minio/storage-minio.xpkg --verbose
          crossplane xpkg push --package-files=minio/storage-minio.xpkg "ghcr.io/versioneer-tech/provider-storage/minio:${{ github.ref_name }}" --verbose
      # - name: Build and publish storage-aws Configuration Package
      #   run: |
      #     cp xrd.yaml aws/xrd.yaml
      #     crossplane xpkg build --package-root=aws --ignore="tests/observed/*,tests/expected/*,tests/required/*" --package-file=aws/storage-aws.xpkg --verbose
      #     crossplane xpkg push --package-files=aws/storage-aws.xpkg "ghcr.io/versioneer-tech/provider-storage/aws:${{ github.ref_name }}" --verbose
      # - name: Build and publish storage-scaleway Configuration Package
      #   run: |
      #     cp xrd.yaml aws/xrd.yaml
      #     crossplane xpkg build --package-root=scaleway --ignore="tests/observed/*,tests/expected/*,tests/required/*" --package-file=aws/storage-scaleway.xpkg --verbose
      #     crossplane xpkg push --package-files=aws/storage-scaleway.xpkg "ghcr.io/versioneer-tech/provider-storage/scaleway:${{ github.ref_name }}" --verbose
  build_docs:
    runs-on: ubuntu-latest
    needs: build_and_publish_configuration_packages
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install mkdocs dependencies
        run: |
          pip install mkdocs mkdocs-material mike
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install crdoc
        run: |
          go install fybrik.io/crdoc@latest
      - name: Generate API docs
        run: |
          sed -i 's/CompositeResourceDefinition/CustomResourceDefinition/' xrd.yaml
          sed -i 's/apiextensions.crossplane.io\/v1/apiextensions.k8s.io\/v1/g' xrd.yaml 
          crdoc -r xrd.yaml -o docs/reference-guides/api.md
      - name: Replace Crossplane Configuration version with tag
        run: |
          find docs -type f -name "*.md" -exec sed -i "s/<!version!>/${{ github.ref_name }}/g" {} +
      - name: Set up GitHub Actions user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@versioneer.at"
      - name: Publish docs to Github pages
        run: |
          git fetch origin gh-pages --depth=1
          mike deploy ${{ github.ref_name }} latest --update-alias --push
          mike set-default latest --push
